# Generated by Django 4.0.6 on 2022-07-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=880)),
                ('product_description', models.TextField()),
                ('product_price', models.FloatField()),
                ('product_photo', models.ImageField(upload_to='')),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('product_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
